kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"get-a-username:1.4"},"fieldPath":"spec.template.spec.containers[?(@.name==\"get-a-username\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  selfLink: /apis/apps/v1/namespaces/guides/deployments/get-a-username
  resourceVersion: '14242026'
  name: get-a-username2
  uid: b5467a18-48e3-4d1a-b3fc-65b5baeb6ce8
  creationTimestamp: '2022-08-30T02:19:59Z'
  generation: 3
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2022-08-30T02:19:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"get-a-username"}':
                  .: {}
                  'f:env':
                    'k:{"name":"LAB_REDIS_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_USER_PASS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_USER_PREFIX"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_USER_PAD_ZERO"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_EXTRA_URLS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_REDIS_PASS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"LAB_USER_COUNT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_USER_ACCESS_TOKEN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_ADMIN_PASS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_MODULE_URLS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LAB_TITLE"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"LAB_DURATION_HOURS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-08-30T02:20:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"get-a-username"}':
                  'f:image': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-09-05T01:45:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"get-a-username"}':
                  'f:env':
                    'k:{"name":"LAB_TITLE"}':
                      'f:value': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-09-05T01:45:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
  namespace: guides
  labels:
    app: get-a-username
    app.kubernetes.io/component: get-a-username
    app.kubernetes.io/instance: get-a-username
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: get-a-username
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: get-a-username
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: get-a-username
          image: >-
            quay.io/openshiftlabs/username-distribution@sha256:d9e1770fbc92f540d19cdceb830fa18ea0d2c31e2fa52685d3e19543131ed662
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: LAB_ADMIN_PASS
              value: openshift
            - name: LAB_DURATION_HOURS
              value: 8h
            - name: LAB_EXTRA_URLS
              value: >-
                https://console-openshift-console.apps.cluster-lmn5m.lmn5m.sandbox600.opentlc.com;OpenShift
                Console,https://codeready-codeready.apps.cluster-lmn5m.lmn5m.sandbox600.opentlc.com;CodeReady
                Workspaces Console
            - name: LAB_MODULE_URLS
              value: >-
                http://web-guides.apps.cluster-lmn5m.lmn5m.sandbox600.opentlc.com/workshop/dg8-workshop/lab/about?userid=%USERNAME%;Getting
                Started with Red Hat DataGrid Hands-on Lab
            - name: LAB_REDIS_HOST
              value: redis
            - name: LAB_REDIS_PASS
              value: redis
            - name: LAB_TITLE
              value: Red Hat DataGrid Workshop - From zero to hero
            - name: LAB_USER_ACCESS_TOKEN
              value: openshift
            - name: LAB_USER_COUNT
              value: '4'
            - name: LAB_USER_PAD_ZERO
              value: 'false'
            - name: LAB_USER_PASS
              value: openshift
            - name: LAB_USER_PREFIX
              value: user
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-08-30T02:20:41Z'
      lastTransitionTime: '2022-08-30T02:20:41Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-09-05T01:45:03Z'
      lastTransitionTime: '2022-08-30T02:19:59Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "get-a-username-79d47b8894" has successfully progressed.
